### ISSUE TITLE
What interface to use the post-processor?

### ISSUE THREAD

**Issue by VictorLamoine** [ros-industrial/robodk_postprocessors#1]
I'm not familiar with Python and i would like this ROS package to be C++ for most of its part.
We want to keep the post processors vanilla.

Is this the best solution?
https://docs.python.org/3/extending/embedding.html

**Comment by gavanderhoorn** [comment]
I'm not saying it isn't possible, but wouldn't it be less work to wrap the scripts in this repository in a ROS service or action server? That would allow you to use whatever client language without having to jump through any hoops.

**Comment by yijiangh** [comment]
Hi @VictorLamoine , nice work for your [PR](https://github.com/ros-industrial/robodk_postprocessors/pull/2), that's a good start!

I want to contribute and help. Can you specify more about the action mechanism that you're thinking about? What is the action data type and how will it work with the planning workflow?

Will it be something similar to the [PostProcessorService](https://gitlab.com/InstitutMaupertuis/fanuc_grinding/blob/indigo-devel/post_processor/srv/PostProcessorService.srv)[1] in your [fanuc_grinding](https://gitlab.com/InstitutMaupertuis/fanuc_grinding)[2] project?

[1] https://gitlab.com/InstitutMaupertuis/fanuc_grinding/blob/indigo-devel/post_processor/srv/PostProcessorService.srv

[2] https://gitlab.com/InstitutMaupertuis/fanuc_grinding

**Comment by VictorLamoine** [comment]
Let's first design/write a Python library (as Gijs suggested) that hides the brand of of the robot without locking things too much.

After that I think we need to design a message that contains everything we need, and it is going to be very hard work.

And finally we can create an action to use the post processor in a robot-agnostic way.

**Comment by VictorLamoine** [comment]
Discussion on discourse: https://discourse.ros.org/t/robodk-post-processors/5663
