### ISSUE TITLE
Provide a way to transfer programs

### ISSUE THREAD

**Issue by VictorLamoine** [ros-industrial/robodk_postprocessors#3]
On Fanuc we can upload textual programs if the robot has the ASCII Upload option.
There seems to be an equivalent for ABB robots: https://github.com/Jmeyer1292/abb_file_suite

**Comment by yijiangh** [comment]
For kuka, personally the easiest way is to generate a .src file and use a usb to copy the file out and paste it in the kuka controller in teach pendant. 

Personally I haven't tried any "direct upload" method for KUKA. But after a bit searching, I found in [robodk's blog](https://robodk.com/blog/)[1] that we can connect kuka controller and PC running RoboDK using FTP (and upload the file) 

(in the link search for key word: "shang" and "Chwan-Hsen, Chen" to check the related post). 

[1] https://robodk.com/blog/

PS:
_It seems that recently KUKA are doing a lot of renovation on their software packages, e.g. they took down RSI and many other packages from their website.  2 years ago, there's a commercial package from kuka called DirectoryLoader especially made for this "file upload" needs._

**Comment by gavanderhoorn** [comment]
Personally I would like to keep transfer of programs separate from the code that lives in this repository. It's a different sort of responsibility.

It's also not something we can solve universally anyway: on Fanuc, ABB and KUKA it's customary to use a textual representation for programs, but there are plenty of (robot) controllers that will only accept a properietary binary encoding of robot programs, which is only output by some proprietary tool (that may only run on Windows).

Let's separate responbilities and keep the postprocessors for what they are good at: transforming a single, common representation into vendor-specific encoding (ie: transpilation).

**Comment by VictorLamoine** [comment]
RoboDK already has FTP upload functions so this is not an issue as tools are already provided to do the job on platforms that support FTP.

https://github.com/ros-industrial/robodk_postprocessors/blob/kinetic-devel/robodk.py#L1207
